export const AppTypes = {
  SHOW_LOADING: "SHOW_LOADING",
  HIDE_LOADING: "HIDE_LOADING",
};
export const autcompleteTypes = {
  CLEARE_AUTOCOMPLETE: "CLEARE_AUTOCOMPLETE",
  GET_AUTOCOMPLETE: "GET_AUTOCOMPLETE",
  GET_AUTOCOMPLETE_SUCCESS: "GET_AUTOCOMPLETE_SUCCESS",
  GET_AUTOCOMPLETE_FAILURE: "GET_AUTOCOMPLETE_FAILURE",
};
export const weeklyWeatherTypes = {
  GET_WEEKLY_WEATHER: "GET_WEEKLY_WEATHER",
  GET_WEEKLY_WEATHER_SUCCESS: "GET_WEEKLY_WEATHER_SUCCESS",
  GET_WEEKLY_WEATHER_FAILURE: "GET_WEEKLY_WEATHER_FAILURE",
};

export const currentWeatherTypes = {
  GET_CURRENT_WEATHER: "GET_CURRENT_WEATHER",
  GET_CURRENT_WEATHER_SUCCESS: "GET_CURRENT_WEATHER_SUCCESS",
  GET_CURRENT_WEATHER_FAILURE: "GET_CURRENT_WEATHER_FAILURE",
};

export const favoritesTypes = {
  GET_FAVORITES: "GET_FAVORITES",
  ADD_FAVORITE: "ADD_FAVORITE",
  DELETE_FAVORITE: "DELETE_FAVORITE",
};
